// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdhEl0WFPK3az8mNjk-noL5NlLbsOSQl0',
    appId: '1:726753562605:web:75372d867f99f76f6c61e4',
    messagingSenderId: '726753562605',
    projectId: 'firabaseappexample',
    authDomain: 'firabaseappexample.firebaseapp.com',
    databaseURL: 'https://firabaseappexample.firebaseio.com',
    storageBucket: 'firabaseappexample.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1_2_Usi9ygEwdA0b4e27DEomSaDMURB0',
    appId: '1:726753562605:android:4b7a9b32b40dca3d6c61e4',
    messagingSenderId: '726753562605',
    projectId: 'firabaseappexample',
    databaseURL: 'https://firabaseappexample.firebaseio.com',
    storageBucket: 'firabaseappexample.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWV6XSz3-sbWktgH1wysT9adf-0IuEQnU',
    appId: '1:726753562605:ios:e5678f2a1b5f1c1a6c61e4',
    messagingSenderId: '726753562605',
    projectId: 'firabaseappexample',
    databaseURL: 'https://firabaseappexample.firebaseio.com',
    storageBucket: 'firabaseappexample.firebasestorage.app',
    androidClientId: '726753562605-ab3kjbi2q42ik0n24ei5o433hsiuuv53.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatProjects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWV6XSz3-sbWktgH1wysT9adf-0IuEQnU',
    appId: '1:726753562605:ios:e5678f2a1b5f1c1a6c61e4',
    messagingSenderId: '726753562605',
    projectId: 'firabaseappexample',
    databaseURL: 'https://firabaseappexample.firebaseio.com',
    storageBucket: 'firabaseappexample.firebasestorage.app',
    androidClientId: '726753562605-ab3kjbi2q42ik0n24ei5o433hsiuuv53.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatProjects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdhEl0WFPK3az8mNjk-noL5NlLbsOSQl0',
    appId: '1:726753562605:web:cc2a4a43b41e1a356c61e4',
    messagingSenderId: '726753562605',
    projectId: 'firabaseappexample',
    authDomain: 'firabaseappexample.firebaseapp.com',
    databaseURL: 'https://firabaseappexample.firebaseio.com',
    storageBucket: 'firabaseappexample.firebasestorage.app',
  );
}
